let blogEntries = [
    {
      name: "Alice",
      week: 1,
      title: "My First Week Exploring Web Dev",
      highlights: "My first week was a whirlwind of discovery. I got hands-on with HTML and learned how each tag contributes to structure and meaning. It was exciting to see a simple webpage come to life from just a few lines of code!",
      skillsLearned: ["HTML", "Semantic Tags"],
      shoutouts: "@Sun",
      emojiMood: "😊",
      quote: "It's like building with digital LEGOs!",
      cardColor: "#FFF3CD",
      profileImageSrc: "./images/bitmoji-hi.png"
    },
    {
      name: "Alice",
      week: 2,
      title: "CSS: Turning Structure into Style",
      highlights: "In my second week, I transitioned from structure to style. I learned how to apply CSS rules to style my HTML pages. I played with colors, spacing, and typography—and finally understood the difference between margin and padding!",
      skillsLearned: ["CSS", "Box Model", "Selectors"],
      shoutouts: "@Bob for the design inspiration",
      emojiMood: "😊",
      quote: "CSS is where creativity meets code.",
      cardColor: "#FDEBD0",
      profileImageSrc: "./images/bitmoji-super.png"
    },
    {
      name: "Alice",
      week: 3,
      title: "JavaScript Foundations",
      highlights: "Week 3 was where the real fun began—JavaScript! I worked with variables, loops, and conditionals. I even created a mini quiz app using basic DOM manipulation. It felt powerful seeing my page respond to user actions.",
      skillsLearned: ["JavaScript", "DOM", "Conditionals"],
      shoutouts: "@Dani for the walkthroughs",
      emojiMood: "😐",
      quote: "JavaScript makes the web come alive.",
      cardColor: "#D5F5E3",
      profileImageSrc: "./images/bitmoji-stars.png"
    },
    {
      name: "Alice",
      week: 4,
      title: "Modular Thinking and Reusability",
      highlights: "This week, I refactored my code to be cleaner and more modular. I created reusable functions and split components into logical blocks. It helped me understand the 'don't repeat yourself' (DRY) principle on a deeper level.",
      skillsLearned: ["Modular Design", "Functions", "DRY Principle"],
      shoutouts: "@Woody for the pairing session",
      emojiMood: "😊",
      quote: "Clean code is kind code.",
      cardColor: "#FADBD8",
      profileImageSrc: "./images/bitmoji-roger.png"
    },
    {
      name: "Alice",
      week: 5,
      title: "Intro to Backend: APIs and Data",
      highlights: "This week I explored APIs and learned how to make GET requests using `fetch()`. Pulling real data into my app blew my mind! I also practiced formatting and displaying JSON data in a user-friendly way.",
      skillsLearned: ["APIs", "fetch()", "Data Parsing"],
      shoutouts: "@Rachel for the backend tips",
      emojiMood: "😊",
      quote: "APIs open doors to real-world power.",
      cardColor: "#D6EAF8",
      profileImageSrc: "./images/bitmoji-thursday.png"
    },
    {
      name: "Alice",
      week: 6,
      title: "Agile Workflows and Team Sprints",
      highlights: "We kicked off our first full-team sprint this week using Agile methodology. I participated in daily stand-ups and contributed to a shared codebase via Git. I learned how vital communication is when coding in a team setting.",
      skillsLearned: ["Agile", "Git", "Team Communication"],
      shoutouts: "@Grace for organizing our sprint board!",
      emojiMood: "😊",
      quote: "Great software is built together.",
      cardColor: "#F9E79F",
      profileImageSrc: "./images/bitmoji-gogo.png"
    },
    {
      name: "Sun",
      week: 7,
      title: "Bug Fixing and Logical Thinking",
      highlights: "Debugging dominated my week! I chased a nasty layout bug caused by a missing `}` and spent hours tracing an asynchronous issue. It was frustrating at first, but solving it taught me how to think more like a detective.",
      skillsLearned: ["Debugging", "Asynchronous JavaScript", "DevTools"],
      shoutouts: "@Frank for reminding me to breathe 😅",
      emojiMood: "😞",
      quote: "Every bug is a puzzle waiting to be solved.",
      cardColor: "#FADBD8",
      profileImageSrc: "./images/bitmoji-panda.png"
    },
    {
      name: "Dani",
      week: 8,
      title: "User Testing and Feedback Loops",
      highlights: "In week 8, I shared my app with real users for the first time. Watching them interact with it opened my eyes to usability issues I’d overlooked. I iterated based on feedback and learned that great UX comes from empathy, not assumptions.",
      skillsLearned: ["User Testing", "Feedback", "Iterative Design"],
      shoutouts: "@Ivy for testing my app on mobile!",
      emojiMood: "😊",
      quote: "Feedback is a feature, not a flaw.",
      cardColor: "#E8DAEF",
      profileImageSrc: "./images/bitmoji-stars.png"
    },
    {
      name: "Chad",
      week: 3,
      title: "Deploying My First Project",
      highlights: "This week was all about launching! I learned how to build and deploy a static site using GitHub Pages. Seeing my work live on the internet felt surreal. I also wrote a short tutorial to help future interns do the same.",
      skillsLearned: ["Deployment", "Build Tools", "Hosting"],
      shoutouts: "@Henry for the Netlify demo",
      emojiMood: "😊",
      quote: "Publishing your work makes it real.",
      cardColor: "#FFD9E6",
      profileImageSrc: "./images/icon-dog.png"
    },
    {
      name: "Rachel",
      week: 4,
      title: "Capstone Kickoff: Team Synergy",
      highlights: "We officially started our capstone project! I joined the frontend team and we brainstormed our MVP. We practiced collaborative Git workflows, sketched user flows, and pitched our first feature set. It felt like a real startup environment.",
      skillsLearned: ["Teamwork", "Git Workflow", "Agile Planning"],
      shoutouts: "@Grace and @Sun for great leadership",
      emojiMood: "😐",
      quote: "Good teamwork makes great products.",
      cardColor: "#D6EAF8",
      profileImageSrc: "./images/bitmoji-best.png"
    },
    {
      name: "Sun",
      week: 9,
      title: "Final Touches & Presentation Prep",
      highlights: "With just one week left, we focused on polishing. I improved accessibility, fixed lingering bugs, and helped design slides for our final demo. Practicing our pitch helped me grow as a communicator, not just a coder.",
      skillsLearned: ["Polish & QA", "Accessibility", "Public Speaking"],
      shoutouts: "@Eve for testing keyboard nav",
      emojiMood: "😊",
      quote: "The little things make the biggest difference.",
      cardColor: "#E9F7EF",
      profileImageSrc: "./images/bitmoji-roger.png"
    },
    {
      name: "Charlie",
      week: 6,
      title: "Designing with Empathy",
      highlights: "This week was about accessible and inclusive design. I reviewed WCAG standards and practiced using screen readers and keyboard navigation. It reminded me that design is for everyone.",
      skillsLearned: ["Accessibility", "WCAG", "Design Thinking"],
      shoutouts: "@Eve for reviewing my form labels",
      emojiMood: "😊",
      quote: "Inclusive design is just good design.",
      cardColor: "#D4EFDF",
      profileImageSrc: "./images/bitmoji-thursday.png"
    },
    {
      name: "Frank",
      week: 5,
      title: "Version Control Victory",
      highlights: "I finally overcame my fear of Git. I practiced branching, merging, and even resolved a conflict solo. It made me realize how essential version control is when collaborating in fast-moving teams.",
      skillsLearned: ["Git", "Branching", "Merge Conflicts"],
      shoutouts: "@Sun for pushing me to try solo rebasing",
      emojiMood: "😐",
      quote: "Git is confusing, until it clicks.",
      cardColor: "#FCE4EC",
      profileImageSrc: "./images/bitmoji-panda.png"
    },
    {
      name: "Ivy",
      week: 10,
      title: "Presenting Like a Pro",
      highlights: "This week we worked on storytelling and delivery for our final presentation. I learned how to build an emotional arc around our project and explain my technical contributions to a non-technical audience.",
      skillsLearned: ["Storytelling", "Presentation", "Confidence"],
      shoutouts: "@Charlie for helping me rehearse!",
      emojiMood: "😊",
      quote: "The story is just as important as the solution.",
      cardColor: "#E0F2F1",
      profileImageSrc: "./images/bitmoji-super.png"
    },
    {
      name: "Brooke",
      week: 9,
      title: "My Week 9 - Deploy b2b vortals",
      highlights: "Fire crime nothing woman middle analysis.",
      skillsLearned: ["React", "CSS", "Responsive Design"],
      shoutouts: "@Richard",
      emojiMood: "😞",
      quote: "Felt stuck, but now I'm flying!",
      cardColor: "#D8BFD8",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Alyssa",
      week: 3,
      title: "My Week 3 - Transform end-to-end functionalities",
      highlights: "Board choose kind quite west while.",
      skillsLearned: ["Express", "APIs"],
      shoutouts: "@Andrew",
      emojiMood: "😞",
      quote: "Felt stuck, but now I'm flying!",
      cardColor: "#FADADD",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Christy",
      week: 5,
      title: "My Week 5 - Brand virtual partnerships",
      highlights: "Movie growth price. Or reveal even today while hit role life.",
      skillsLearned: ["HTML", "React", "Node.js"],
      shoutouts: "@Susan",
      emojiMood: "😐",
      quote: "Pixels, problems, progress.",
      cardColor: "#FADADD",
      profileImageSrc: "./images/bitmoji-birthday.png"
    },
    {
      name: "Jasmine",
      week: 8,
      title: "My Week 8 - Brand best-of-breed roi",
      highlights: "Than team rich shake peace feel.",
      skillsLearned: ["Figma", "Node.js"],
      shoutouts: "@Melissa",
      emojiMood: "😞",
      quote: "From chaos to clarity!",
      cardColor: "#D8BFD8",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Michelle",
      week: 1,
      title: "My Week 1 - Monetize customized interfaces",
      highlights: "Mention health often media compare environmental. Raise ten television.",
      skillsLearned: ["GitHub", "Responsive Design", "Figma"],
      shoutouts: "@Nicholas",
      emojiMood: "😞",
      quote: "It's like building with digital LEGOs!",
      cardColor: "#FDFD96",
      profileImageSrc: "./images/bitmoji-panda.png"
    },
    {
      name: "Denise",
      week: 2,
      title: "My Week 2 - Repurpose clicks-and-mortar web-readiness",
      highlights: "Anything hair sort bag current down stage. Expect experience let wonder.",
      skillsLearned: ["Git", "Tailwind", "UI/UX", "Express"],
      shoutouts: "@Kenneth",
      emojiMood: "😊",
      quote: "Pixels, problems, progress.",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/bitmoji-rating5.png"
    },
    {
      name: "Katrina",
      week: 4,
      title: "My Week 4 - Implement wireless infrastructures",
      highlights: "Actually always break himself turn make.",
      skillsLearned: ["CSS", "GitHub", "HTML", "JavaScript"],
      shoutouts: "@Daniel",
      emojiMood: "😐",
      quote: "From chaos to clarity!",
      cardColor: "#FDFD96",
      profileImageSrc: "./images/bitmoji-birthday.png"
    },
    {
      name: "Hannah",
      week: 1,
      title: "My Week 1 - Exploit compelling markets",
      highlights: "Ball significant pattern describe paper economy. Health pick quickly note sit draw cost.",
      skillsLearned: ["APIs", "Git"],
      shoutouts: "@Joshua",
      emojiMood: "😊",
      quote: "Still lost, but now with style!",
      cardColor: "#FDFD96",
      profileImageSrc: "./images/bitmoji-panda.png"
    },
    {
      name: "Andrew",
      week: 1,
      title: "My Week 1 - Facilitate end-to-end initiatives",
      highlights: "Draw home to pretty.",
      skillsLearned: ["Tailwind", "HTML", "Express", "GitHub"],
      shoutouts: "@Jamie",
      emojiMood: "😊",
      quote: "Every line of code is a step closer to confidence.",
      cardColor: "#FADADD",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Shannon",
      week: 4,
      title: "My Week 4 - Brand turn-key methodologies",
      highlights: "Upon lay purpose student do debate assume professional. Specific everyone ahead interesting culture most.",
      skillsLearned: ["APIs", "Figma"],
      shoutouts: "@Jessica",
      emojiMood: "😊",
      quote: "Pixels, problems, progress.",
      cardColor: "#D8BFD8",
      profileImageSrc: "./images/bitmoji-thursday.png"
    },
    {
      name: "Denise",
      week: 1,
      title: "My Week 1 - Deploy plug-and-play solutions",
      highlights: "Argue two painting everything wall. Radio important service history receive.",
      skillsLearned: ["Git", "Express"],
      shoutouts: "@Aaron",
      emojiMood: "😞",
      quote: "It's like building with digital LEGOs!",
      cardColor: "#A7C7E7",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "William",
      week: 6,
      title: "My Week 6 - Deploy cross-platform schemas",
      highlights: "Force form fact teach Mrs Mr charge. Loss expert whether air meeting peace.",
      skillsLearned: ["UI/UX", "APIs"],
      shoutouts: "@Elizabeth",
      emojiMood: "😊",
      quote: "Felt stuck, but now I'm flying!",
      cardColor: "white",
      profileImageSrc: "./images/icon-dog.png"
    },
    {
      name: "Charles",
      week: 2,
      title: "My Week 2 - Repurpose integrated supply-chains",
      highlights: "Fight live dark.",
      skillsLearned: ["Express", "HTML", "Debugging", "Tailwind"],
      shoutouts: "@Michael",
      emojiMood: "😊",
      quote: "Pixels, problems, progress.",
      cardColor: "#A7C7E7",
      profileImageSrc: "./images/bitmoji-rating5.png"
    },
    {
      name: "Tracy",
      week: 9,
      title: "My Week 9 - Incubate killer schemas",
      highlights: "Item station future parent.",
      skillsLearned: ["Express", "GitHub", "Node.js"],
      shoutouts: "@Jennifer",
      emojiMood: "😐",
      quote: "It's like building with digital LEGOs!",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/icon-dog.png"
    },
    {
      name: "Trevor",
      week: 2,
      title: "My Week 2 - Repurpose frictionless schemas",
      highlights: "Own prevent crime notice field.",
      skillsLearned: ["React", "UI/UX", "APIs", "Express"],
      shoutouts: "@Darrell",
      emojiMood: "😊",
      quote: "Every line of code is a step closer to confidence.",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Andrew",
      week: 4,
      title: "My Week 4 - Incentivize e-business content",
      highlights: "A example feeling have help arm yard.",
      skillsLearned: ["Node.js", "Express", "Bootstrap"],
      shoutouts: "@Wesley",
      emojiMood: "😐",
      quote: "Still lost, but now with style!",
      cardColor: "#D8BFD8",
      profileImageSrc: "./images/bitmoji-rating5.png"
    },
    {
      name: "Adam",
      week: 7,
      title: "My Week 7 - Implement transparent solutions",
      highlights: "Everybody remember issue model financial executive. Challenge huge camera myself cause catch mention.",
      skillsLearned: ["Git", "Express", "HTML"],
      shoutouts: "@Lindsey",
      emojiMood: "😊",
      quote: "It's like building with digital LEGOs!",
      cardColor: "#FADADD",
      profileImageSrc: "./images/bitmoji-panda.png"
    },
    {
      name: "William",
      week: 7,
      title: "My Week 7 - Transform innovative networks",
      highlights: "Pretty very ahead both certain experience. State foreign music before get clearly.",
      skillsLearned: ["React", "Git", "UI/UX"],
      shoutouts: "@Andrea",
      emojiMood: "😐",
      quote: "Every line of code is a step closer to confidence.",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/bitmoji-thursday.png"
    },
    {
      name: "Mark",
      week: 2,
      title: "My Week 2 - Utilize extensible communities",
      highlights: "Education effort picture respond early. If describe story seat.",
      skillsLearned: ["Responsive Design", "React", "Git"],
      shoutouts: "@Dale",
      emojiMood: "😞",
      quote: "Turning coffee into code, one function at a time.",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/bitmoji-rating5.png"
    },
    {
      name: "Ariana",
      week: 5,
      title: "My Week 5 - Scale dot-com web-readiness",
      highlights: "Allow large soldier important drop police. Stuff race success decade.",
      skillsLearned: ["Tailwind", "Responsive Design", "React"],
      shoutouts: "@Lisa",
      emojiMood: "😐",
      quote: "It's like building with digital LEGOs!",
      cardColor: "#FADADD",
      profileImageSrc: "./images/bitmoji-birthday.png"
    },
    {
      name: "Benjamin",
      week: 2,
      title: "My Week 2 - Transform integrated applications",
      highlights: "Name share whose far.",
      skillsLearned: ["HTML", "UI/UX", "Tailwind", "APIs"],
      shoutouts: "@William",
      emojiMood: "😞",
      quote: "Felt stuck, but now I'm flying!",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/bitmoji-thursday.png"
    },
    {
      name: "Jessica",
      week: 4,
      title: "My Week 4 - Generate efficient models",
      highlights: "Spend program first relate structure kid she. College move time major exactly stay.",
      skillsLearned: ["GitHub", "HTML", "Tailwind", "Responsive Design"],
      shoutouts: "@Sara",
      emojiMood: "😊",
      quote: "Felt stuck, but now I'm flying!",
      cardColor: "#A7C7E7",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Kathryn",
      week: 5,
      title: "My Week 5 - Harness real-time e-commerce",
      highlights: "Power listen figure yourself hundred she tree. Author sense affect include something entire thank.",
      skillsLearned: ["Express", "Node.js"],
      shoutouts: "@Christine",
      emojiMood: "😊",
      quote: "Still lost, but now with style!",
      cardColor: "#FDFD96",
      profileImageSrc: "./images/bitmoji-stars.png"
    },
    {
      name: "Jennifer",
      week: 7,
      title: "My Week 7 - Seize bricks-and-clicks mindshare",
      highlights: "Attorney without first soldier must mouth. Sea professor allow something go tonight.",
      skillsLearned: ["Node.js", "GitHub"],
      shoutouts: "@Craig",
      emojiMood: "😐",
      quote: "Every line of code is a step closer to confidence.",
      cardColor: "#FDFD96",
      profileImageSrc: "./images/bitmoji-rating5.png"
    },
    {
      name: "Lauren",
      week: 9,
      title: "My Week 9 - Exploit seamless supply-chains",
      highlights: "Room society answer line either name value. Phone unit Mrs.",
      skillsLearned: ["GitHub", "Node.js"],
      shoutouts: "@Rebekah",
      emojiMood: "😊",
      quote: "Still lost, but now with style!",
      cardColor: "#D8BFD8",
      profileImageSrc: "./images/bitmoji-stars.png"
    },
    {
      name: "Audrey",
      week: 1,
      title: "My Week 1 - Seize best-of-breed platforms",
      highlights: "Travel use use effort.",
      skillsLearned: ["HTML", "Express", "Responsive Design"],
      shoutouts: "@Lisa",
      emojiMood: "😞",
      quote: "It's like building with digital LEGOs!",
      cardColor: "white",
      profileImageSrc: "./images/bitmoji-hi.png"
    },
    {
      name: "Kenneth",
      week: 7,
      title: "My Week 7 - Scale seamless deliverables",
      highlights: "Coach them describe after what. Hotel throw relate.",
      skillsLearned: ["JavaScript", "React", "HTML"],
      shoutouts: "@Andrea",
      emojiMood: "😐",
      quote: "Still lost, but now with style!",
      cardColor: "white",
      profileImageSrc: "./images/icon-dog.png"
    },
    {
      name: "Daniel",
      week: 5,
      title: "My Week 5 - Architect turn-key synergies",
      highlights: "Kitchen research happy Congress easy be.",
      skillsLearned: ["GitHub", "APIs", "Node.js", "Figma"],
      shoutouts: "@Christopher",
      emojiMood: "😞",
      quote: "It's like building with digital LEGOs!",
      cardColor: "#D8BFD8",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Justin",
      week: 5,
      title: "My Week 5 - Optimize value-added e-tailers",
      highlights: "Citizen above conference believe father individual hospital. Recent financial no beat work star lawyer.",
      skillsLearned: ["Bootstrap", "GitHub"],
      shoutouts: "@Kevin",
      emojiMood: "😞",
      quote: "Still lost, but now with style!",
      cardColor: "#FADADD",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Lauren",
      week: 3,
      title: "My Week 3 - Reinvent out-of-the-box functionalities",
      highlights: "Speech gun outside decision. Attention thing fill rock community current election lot.",
      skillsLearned: ["GitHub", "Bootstrap"],
      shoutouts: "@Jasmine",
      emojiMood: "😊",
      quote: "It's like building with digital LEGOs!",
      cardColor: "white",
      profileImageSrc: "./images/bitmoji-birthday.png"
    },
    {
      name: "Robert",
      week: 7,
      title: "My Week 7 - Innovate transparent architectures",
      highlights: "Oil today can whatever expect along leave.",
      skillsLearned: ["Git", "GitHub"],
      shoutouts: "@William",
      emojiMood: "😞",
      quote: "Still lost, but now with style!",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/bitmoji-hi.png"
    },
    {
      name: "Charles",
      week: 2,
      title: "My Week 2 - Engage customized schemas",
      highlights: "Little process local town popular. Two goal cultural reach.",
      skillsLearned: ["CSS", "Figma", "Tailwind"],
      shoutouts: "@Cynthia",
      emojiMood: "😐",
      quote: "Every line of code is a step closer to confidence.",
      cardColor: "#D8BFD8",
      profileImageSrc: "./images/bitmoji-thursday.png"
    },
    {
      name: "April",
      week: 9,
      title: "My Week 9 - Target open-source deliverables",
      highlights: "Organization friend reduce four entire. Direction even sport meeting go.",
      skillsLearned: ["Node.js", "GitHub", "Debugging", "React"],
      shoutouts: "@Emily",
      emojiMood: "😊",
      quote: "Felt stuck, but now I'm flying!",
      cardColor: "#D8BFD8",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Tyler",
      week: 9,
      title: "My Week 9 - Envisioneer world-class architectures",
      highlights: "Garden seat this receive rather full. Single receive believe technology.",
      skillsLearned: ["React", "Debugging", "Responsive Design"],
      shoutouts: "@Kelsey",
      emojiMood: "😊",
      quote: "From chaos to clarity!",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/bitmoji-rating5.png"
    },
    {
      name: "Summer",
      week: 4,
      title: "My Week 4 - Reinvent integrated initiatives",
      highlights: "Interest or admit society its teach affect. None reach rule room bank.",
      skillsLearned: ["Bootstrap", "CSS"],
      shoutouts: "@Christine",
      emojiMood: "😞",
      quote: "Pixels, problems, progress.",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/bitmoji-birthday.png"
    },
    {
      name: "Aaron",
      week: 6,
      title: "My Week 6 - Iterate impactful vortals",
      highlights: "Themselves law degree finish.",
      skillsLearned: ["UI/UX", "CSS"],
      shoutouts: "@John",
      emojiMood: "😊",
      quote: "From chaos to clarity!",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/bitmoji-hi.png"
    },
    {
      name: "Sandra",
      week: 9,
      title: "My Week 9 - Facilitate intuitive initiatives",
      highlights: "Add us know through record under. Impact give teach break answer left.",
      skillsLearned: ["Tailwind", "Git", "CSS", "Figma"],
      shoutouts: "@Tammy",
      emojiMood: "😊",
      quote: "Still lost, but now with style!",
      cardColor: "#A7C7E7",
      profileImageSrc: "./images/bitmoji-rating5.png"
    },
    {
      name: "Cassandra",
      week: 5,
      title: "My Week 5 - Utilize global functionalities",
      highlights: "House different system student main detail whether scientist.",
      skillsLearned: ["Git", "Express"],
      shoutouts: "@Mariah",
      emojiMood: "😐",
      quote: "Still lost, but now with style!",
      cardColor: "white",
      profileImageSrc: "./images/bitmoji-birthday.png"
    },
    {
      name: "Kristy",
      week: 1,
      title: "My Week 1 - Monetize open-source technologies",
      highlights: "Generation meet already wish gun. All and wife though.",
      skillsLearned: ["Responsive Design", "JavaScript"],
      shoutouts: "@Lisa",
      emojiMood: "😐",
      quote: "It's like building with digital LEGOs!",
      cardColor: "#FDFD96",
      profileImageSrc: "./images/bitmoji-birthday.png"
    },
    {
      name: "Paul",
      week: 1,
      title: "My Week 1 - Extend interactive synergies",
      highlights: "Strong spend voice president. Nor Mrs low nothing his role.",
      skillsLearned: ["Figma", "Tailwind", "UI/UX"],
      shoutouts: "@Richard",
      emojiMood: "😊",
      quote: "Every line of code is a step closer to confidence.",
      cardColor: "#A7C7E7",
      profileImageSrc: "./images/bitmoji-panda.png"
    },
    {
      name: "Michael",
      week: 1,
      title: "My Week 1 - Reinvent transparent systems",
      highlights: "Time physical under blue.",
      skillsLearned: ["Node.js", "Bootstrap", "CSS"],
      shoutouts: "@Tony",
      emojiMood: "😐",
      quote: "Still lost, but now with style!",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/bitmoji-hi.png"
    },
    {
      name: "Adam",
      week: 3,
      title: "My Week 3 - Incentivize granular paradigms",
      highlights: "Miss area issue politics so study seem. Worker present thus under across.",
      skillsLearned: ["APIs", "CSS", "Responsive Design", "React"],
      shoutouts: "@Diana",
      emojiMood: "😐",
      quote: "From chaos to clarity!",
      cardColor: "#D8BFD8",
      profileImageSrc: "./images/bitmoji-thursday.png"
    },
    {
      name: "Bryan",
      week: 4,
      title: "My Week 4 - Seize transparent portals",
      highlights: "Member security conference goal role center network. Keep long American leg camera city top.",
      skillsLearned: ["Express", "GitHub", "Git", "CSS"],
      shoutouts: "@Jacob",
      emojiMood: "😐",
      quote: "Still lost, but now with style!",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Shawn",
      week: 8,
      title: "My Week 8 - Harness one-to-one e-services",
      highlights: "Vote home either true information any change.",
      skillsLearned: ["Node.js", "Debugging", "GitHub", "Tailwind"],
      shoutouts: "@Monica",
      emojiMood: "😊",
      quote: "I never thought debugging could be fun!",
      cardColor: "#A7C7E7",
      profileImageSrc: "./images/bitmoji-hi.png"
    },
    {
      name: "Nicole",
      week: 8,
      title: "My Week 8 - Reinvent scalable e-markets",
      highlights: "Apply nice off money than blue summer. Population keep public professional writer question effect.",
      skillsLearned: ["Git", "CSS", "Node.js", "Express"],
      shoutouts: "@Angela",
      emojiMood: "😞",
      quote: "Still lost, but now with style!",
      cardColor: "#FADADD",
      profileImageSrc: "./images/icon-dog.png"
    },
    {
      name: "Vanessa",
      week: 3,
      title: "My Week 3 - Orchestrate efficient experiences",
      highlights: "Bit avoid often similar. Research season store.",
      skillsLearned: ["Tailwind", "GitHub", "Responsive Design", "Git"],
      shoutouts: "@Ashley",
      emojiMood: "😊",
      quote: "Turning coffee into code, one function at a time.",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "David",
      week: 6,
      title: "My Week 6 - Evolve vertical models",
      highlights: "Table involve administration next medical identify.",
      skillsLearned: ["JavaScript", "Node.js", "Tailwind"],
      shoutouts: "@Carol",
      emojiMood: "😞",
      quote: "Felt stuck, but now I'm flying!",
      cardColor: "#FADADD",
      profileImageSrc: "./images/icon-cat.png"
    },
    {
      name: "Nicholas",
      week: 9,
      title: "My Week 9 - Reinvent best-of-breed web-readiness",
      highlights: "Moment look again actually reveal.",
      skillsLearned: ["Debugging", "Git", "Figma", "React"],
      shoutouts: "@Tiffany",
      emojiMood: "😐",
      quote: "Every line of code is a step closer to confidence.",
      cardColor: "#FADADD",
      profileImageSrc: "./images/icon-dog.png"
    },
    {
      name: "Denise",
      week: 9,
      title: "My Week 9 - Seize back-end architectures",
      highlights: "Each radio director ball machine this.",
      skillsLearned: ["React", "Responsive Design", "GitHub"],
      shoutouts: "@Patrick",
      emojiMood: "😐",
      quote: "It's like building with digital LEGOs!",
      cardColor: "white",
      profileImageSrc: "./images/bitmoji-stars.png"
    },
    {
      name: "Rachel",
      week: 1,
      title: "My Week 1 - Orchestrate world-class niches",
      highlights: "Scene them gas phone benefit any onto.",
      skillsLearned: ["JavaScript", "GitHub", "React"],
      shoutouts: "@Patricia",
      emojiMood: "😐",
      quote: "Every line of code is a step closer to confidence.",
      cardColor: "#C1E1C1",
      profileImageSrc: "./images/bitmoji-birthday.png"
    }
 
  ];      