let blogEntries = [
    {
      name: "Alice",
      week: 1,
      title: "My First Week Exploring Web Dev",
      highlights: "My first week was a whirlwind of discovery. I got hands-on with HTML and learned how each tag contributes to structure and meaning. It was exciting to see a simple webpage come to life from just a few lines of code!",
      skillsLearned: ["HTML", "Semantic Tags"],
      shoutouts: "@Sun",
      emojiMood: "😊",
      quote: "It's like building with digital LEGOs!",
      cardColor: "#FFF3CD",
      profileImageSrc: "./images/bitmoji-hi.png"
    },
    {
      name: "Alice",
      week: 2,
      title: "CSS: Turning Structure into Style",
      highlights: "In my second week, I transitioned from structure to style. I learned how to apply CSS rules to style my HTML pages. I played with colors, spacing, and typography—and finally understood the difference between margin and padding!",
      skillsLearned: ["CSS", "Box Model", "Selectors"],
      shoutouts: "@Bob for the design inspiration",
      emojiMood: "😊",
      quote: "CSS is where creativity meets code.",
      cardColor: "#FDEBD0",
      profileImageSrc: "./images/bitmoji-super.png"
    },
    {
      name: "Alice",
      week: 3,
      title: "JavaScript Foundations",
      highlights: "Week 3 was where the real fun began—JavaScript! I worked with variables, loops, and conditionals. I even created a mini quiz app using basic DOM manipulation. It felt powerful seeing my page respond to user actions.",
      skillsLearned: ["JavaScript", "DOM", "Conditionals"],
      shoutouts: "@Dani for the walkthroughs",
      emojiMood: "😐",
      quote: "JavaScript makes the web come alive.",
      cardColor: "#D5F5E3",
      profileImageSrc: "./images/bitmoji-stars.png"
    },
    {
      name: "Alice",
      week: 4,
      title: "Modular Thinking and Reusability",
      highlights: "This week, I refactored my code to be cleaner and more modular. I created reusable functions and split components into logical blocks. It helped me understand the 'don't repeat yourself' (DRY) principle on a deeper level.",
      skillsLearned: ["Modular Design", "Functions", "DRY Principle"],
      shoutouts: "@Woody for the pairing session",
      emojiMood: "😊",
      quote: "Clean code is kind code.",
      cardColor: "#FADBD8",
      profileImageSrc: "./images/bitmoji-roger.png"
    },
    {
      name: "Alice",
      week: 5,
      title: "Intro to Backend: APIs and Data",
      highlights: "This week I explored APIs and learned how to make GET requests using `fetch()`. Pulling real data into my app blew my mind! I also practiced formatting and displaying JSON data in a user-friendly way.",
      skillsLearned: ["APIs", "fetch()", "Data Parsing"],
      shoutouts: "@Rachel for the backend tips",
      emojiMood: "😊",
      quote: "APIs open doors to real-world power.",
      cardColor: "#D6EAF8",
      profileImageSrc: "./images/bitmoji-thursday.png"
    },
    {
      name: "Alice",
      week: 6,
      title: "Agile Workflows and Team Sprints",
      highlights: "We kicked off our first full-team sprint this week using Agile methodology. I participated in daily stand-ups and contributed to a shared codebase via Git. I learned how vital communication is when coding in a team setting.",
      skillsLearned: ["Agile", "Git", "Team Communication"],
      shoutouts: "@Grace for organizing our sprint board!",
      emojiMood: "😊",
      quote: "Great software is built together.",
      cardColor: "#F9E79F",
      profileImageSrc: "./images/bitmoji-gogo.png"
    },
    {
      name: "Sun",
      week: 7,
      title: "Bug Fixing and Logical Thinking",
      highlights: "Debugging dominated my week! I chased a nasty layout bug caused by a missing `}` and spent hours tracing an asynchronous issue. It was frustrating at first, but solving it taught me how to think more like a detective.",
      skillsLearned: ["Debugging", "Asynchronous JavaScript", "DevTools"],
      shoutouts: "@Frank for reminding me to breathe 😅",
      emojiMood: "😞",
      quote: "Every bug is a puzzle waiting to be solved.",
      cardColor: "#FADBD8",
      profileImageSrc: "./images/bitmoji-panda.png"
    },
    {
      name: "Dani",
      week: 8,
      title: "User Testing and Feedback Loops",
      highlights: "In week 8, I shared my app with real users for the first time. Watching them interact with it opened my eyes to usability issues I’d overlooked. I iterated based on feedback and learned that great UX comes from empathy, not assumptions.",
      skillsLearned: ["User Testing", "Feedback", "Iterative Design"],
      shoutouts: "@Ivy for testing my app on mobile!",
      emojiMood: "😊",
      quote: "Feedback is a feature, not a flaw.",
      cardColor: "#E8DAEF",
      profileImageSrc: "./images/bitmoji-stars.png"
    },
    {
      name: "Chad",
      week: 3,
      title: "Deploying My First Project",
      highlights: "This week was all about launching! I learned how to build and deploy a static site using GitHub Pages. Seeing my work live on the internet felt surreal. I also wrote a short tutorial to help future interns do the same.",
      skillsLearned: ["Deployment", "Build Tools", "Hosting"],
      shoutouts: "@Henry for the Netlify demo",
      emojiMood: "😊",
      quote: "Publishing your work makes it real.",
      cardColor: "#FFD9E6",
      profileImageSrc: "./images/icon-dog.png"
    },
    {
      name: "Rachel",
      week: 4,
      title: "Capstone Kickoff: Team Synergy",
      highlights: "We officially started our capstone project! I joined the frontend team and we brainstormed our MVP. We practiced collaborative Git workflows, sketched user flows, and pitched our first feature set. It felt like a real startup environment.",
      skillsLearned: ["Teamwork", "Git Workflow", "Agile Planning"],
      shoutouts: "@Grace and @Sun for great leadership",
      emojiMood: "😐",
      quote: "Good teamwork makes great products.",
      cardColor: "#D6EAF8",
      profileImageSrc: "./images/bitmoji-best.png"
    },
    {
      name: "Sun",
      week: 9,
      title: "Final Touches & Presentation Prep",
      highlights: "With just one week left, we focused on polishing. I improved accessibility, fixed lingering bugs, and helped design slides for our final demo. Practicing our pitch helped me grow as a communicator, not just a coder.",
      skillsLearned: ["Polish & QA", "Accessibility", "Public Speaking"],
      shoutouts: "@Eve for testing keyboard nav",
      emojiMood: "😊",
      quote: "The little things make the biggest difference.",
      cardColor: "#E9F7EF",
      profileImageSrc: "./images/bitmoji-roger.png"
    },
    {
      name: "Charlie",
      week: 6,
      title: "Designing with Empathy",
      highlights: "This week was about accessible and inclusive design. I reviewed WCAG standards and practiced using screen readers and keyboard navigation. It reminded me that design is for everyone.",
      skillsLearned: ["Accessibility", "WCAG", "Design Thinking"],
      shoutouts: "@Eve for reviewing my form labels",
      emojiMood: "😊",
      quote: "Inclusive design is just good design.",
      cardColor: "#D4EFDF",
      profileImageSrc: "./images/bitmoji-thursday.png"
    },
    {
      name: "Frank",
      week: 5,
      title: "Version Control Victory",
      highlights: "I finally overcame my fear of Git. I practiced branching, merging, and even resolved a conflict solo. It made me realize how essential version control is when collaborating in fast-moving teams.",
      skillsLearned: ["Git", "Branching", "Merge Conflicts"],
      shoutouts: "@Sun for pushing me to try solo rebasing",
      emojiMood: "😐",
      quote: "Git is confusing, until it clicks.",
      cardColor: "#FCE4EC",
      profileImageSrc: "./images/bitmoji-panda.png"
    },
    {
      name: "Ivy",
      week: 10,
      title: "Presenting Like a Pro",
      highlights: "This week we worked on storytelling and delivery for our final presentation. I learned how to build an emotional arc around our project and explain my technical contributions to a non-technical audience.",
      skillsLearned: ["Storytelling", "Presentation", "Confidence"],
      shoutouts: "@Charlie for helping me rehearse!",
      emojiMood: "😊",
      quote: "The story is just as important as the solution.",
      cardColor: "#E0F2F1",
      profileImageSrc: "./images/bitmoji-super.png"
    }
  ];      